<?php

const STATUS_INACTIVE = 0;

const COMMAND_TYPE_TOKEN_COIN_PAIR = 18;
const COMMAND_TYPE_DELETE_FAILED_JOBS = 27;

const BOT_SYNC_MARKET_PRICE = 'neutral';
const BOT_INCREASE_MARKET_PRICE = 'increase';
const BOT_DECREASE_MARKET_PRICE = 'decrease';
const BOT_RANDOM_MARKET_PRICE = 'random';

const RATE_SOURCE_DEFAULT = 'default';
const RATE_SOURCE_DB = 'rate_db';
const RATE_SOURCE_EXTERNAL = 'external';

const PERCENT_LEFT_LEN = 1;
const PERCENT_DECIMAL = 3;
const MAX_PERCENT = 10;
const MIN_PERCENT = 0.01;

const BOT_ORDER_PROCESS_REDIS = 2;
const BOT_ORDER_PROCESS_DIRECT_COMMAND = 1;
const MATIC_TOKEN = 44;

const THEME_GREEN = 'green';
const THEME_YELLOW = 'yellow';
const THEME_BLUE = 'blue';

const TRANSACTION_FILTER_ALL = 0;
const TRANSACTION_FILTER_BOT_TO_BOT = 1;
const TRANSACTION_FILTER_BOT_TO_USER = 2;
const TRANSACTION_FILTER_USER_TO_USER = 3;

const LOGIN_WITH_FACEBOOK = 1;
const LOGIN_WITH_GOOGLE = 2;
const LOGIN_WITH_TWITTER = 3;
const LOGIN_WITH_APPLE = 4;

const WALLET_GENERATE_BY_COIN = 1;
const WALLET_GENERATE_BY_USER = 2;